VCMS.MVC4.Web/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VCMS.MVC4.Data;
using VCMS.MVC4.Web;
using EntityFramework.Extensions;
namespace VCMS.MVC4.Web.Areas.Admin.Controllers
{
    public class MenuController : VCMSAdminController
    {
        //
        // GET: /Menu/

        public ActionResult Index()
        {
            using (DataContext db = new DataContext())
            {
                var items = db.MenuItems.Include("MenuItemDetail").OrderBy(m=>m.SortOrder).ToList();
                return View(items);
            }
        }

        public ActionResult Create() {
            using (DataContext db = new DataContext())
            {
                var model = new MenuItem { MenuItemDetail = VList<MenuItemDetail>.Create(SiteConfig.Languages) };
                ViewBag.ArticleTypeList = new SelectList(db.ArticleTypes.Include("ArticleTypeDetail").ToList(), "Id", "Name");
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            if (ModelState.IsValid)
            {
                using (DataContext db = new DataContext())
                {
                    MenuItem model = new MenuItem();
                    TryUpdateModel(model);
                    model.MenuItemDetail = new VList<MenuItemDetail>();

                    foreach (var item in SiteConfig.Languages)
                    {
                        model.MenuItemDetail.Add(new MenuItemDetail() { LanguageId = item.Id, Text = Request["txtName" + item.Id.ToString()] });
                    }
                    db.MenuItems.Add(model);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }


        public ActionResult Edit(int id)
        {
            using (DataContext db = new DataContext())
            {
                var model = db.MenuItems.Include("MenuItemDetail").FirstOrDefault(m => m.Id == id);

                if (model == null)
                    return HttpNotFound();
                var missing = SiteConfig.Languages.Where(l => !model.MenuItemDetail.Any(cd => cd.LanguageId == l.Id)).Select(l => l.Id).ToList();
                missing.ForEach(m => { model.MenuItemDetail.Add(new MenuItemDetail { LanguageId = m }); });
                ViewBag.ArticleTypeList = new SelectList(db.ArticleTypes.Include("ArticleTypeDetail").ToList(), "Id", "Name");
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                using (DataContext db = new DataContext())
                {
                    MenuItem model = db.MenuItems.Include("MenuItemDetail").FirstOrDefault(m => m.Id == id);
                    TryUpdateModel(model);
                    model.MenuItemDetail = new VList<MenuItemDetail>();

                    foreach (var item in SiteConfig.Languages)
                    {
                        model.MenuItemDetail.Add(new MenuItemDetail() { LanguageId = item.Id, Text = Request["txtName" + item.Id.ToString()] });
                    }
                    //db.MenuItems.Attach(model);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(string id)
        {
            using (DataContext db = new DataContext())
            {
                int[] ids = id.Split(new char[] { ',' }).Select(s => int.Parse(s)).ToArray();

                db.MenuItems.Delete(af => ids.Contains(af.Id));
                db.SaveChanges();
                return Json(new { Status = 0, Message = "OK" });
            }
        }
        [HttpPost]
        public ActionResult UpdateOrder(string id, string order)
        {
            using (DataContext db = new DataContext())
            {
                var ids = id.Split(new char[] { ',' }).Select(s => int.Parse(s)).ToList();
                var orders = order.Split(new char[] { ',' }).Select(s => int.Parse(s)).ToList();

                var list = db.MenuItems.Where(c => ids.Contains(c.Id)).ToList();
                list.ForEach(c => { c.SortOrder = orders[ids.IndexOf(c.Id)]; });
                //db.Categories.Update(c => ids.Contains(c.Id), c2 => new Category { SortOrder = orders[ids.IndexOf(c2.Id)] });
                db.SaveChanges();
                return Json(new { Status = 0, Message = "OK" });
            }
        }
    }
}

VCMS.MVC4.Web/Controllers/WidgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VCMS.MVC4.Data;
using System.Data.Entity;
using System.Web.WebPages;
using VCMS.MVC4.Web.App_Start;


namespace VCMS.MVC4.Web.Controllers
{
    [HandleError]

    public class WidgetController :Controller
    {
        public ActionResult Widget(string name)
        {

            using (DataContext db = new DataContext())
            {
                var widgets = PageContext.Widgets;
                Widget widget = null;
                if (widgets != null && widgets.Any(w => w.Code.Equals(name, StringComparison.OrdinalIgnoreCase)))
                    widget = widgets.FirstOrDefault(w => w.Code.Equals(name, StringComparison.OrdinalIgnoreCase));
                else
                 widget = db.Widget.Include(a => a.WidgetDetail).Include(w=>w.ArticleType).FirstOrDefault(a => a.Code.Equals(name, StringComparison.OrdinalIgnoreCase));
                if (widget == null)
                    return Content(string.Format("Widget {0} not found!", name));
                else
                {
                    widget.LanguageId = SiteConfig.LanguageId;
                    if (widget.WidgetType == WidgetType.HTML)
                        return Content(widget.Value);
                    if (widget.WidgetType == WidgetType.WEBPLUGIN)
                        return Content((!string.IsNullOrWhiteSpace(widget.WidgetDetail[1].Value) ? widget.WidgetDetail[1].Value : ""));
                }
                if (!string.IsNullOrWhiteSpace(widget.WidgetView))
                {
                    var mode = SiteConfig.Mode;
                    var view = "";
                    //var type = db.ArticleTypes.FirstOrDefault(a => a.Id == widget.ArticleTypeId);
                    var type = widget.ArticleType;
                    if (type != null)
                        view = type.Code;
                    var widgetview = widget.WidgetView.Trim().ToString();
                    if (!string.IsNullOrWhiteSpace(mode))
                    {
                        ViewEngineResult resultview = ViewEngines.Engines.FindView(ControllerContext, view + "/" + widget.WidgetView.ToString() + mode, null);
                        widgetview = resultview.View != null ? widgetview += mode : widgetview;
                    }
                    
                    ViewEngineResult result = ViewEngines.Engines.FindView(ControllerContext, view + "/" + widgetview, null);
                    if (result.View != null)
                        return PartialView(view + "/" + widgetview, widget);

                    result = ViewEngines.Engines.FindView(ControllerContext, widget.WidgetView.ToString(), null);
                    if (result.View != null)
                        return PartialView(widget.WidgetView.ToString(), widget);
                }
                else
                    return Content(string.Format("Widget {0} not found views!", name));
            }
            return Content(string.Format("Widget {0} not found!", name));
        }
        public ActionResult WidgetGroup(string name)
        {
            using (DataContext db = new DataContext())
            {
                //var group = db.WidgetGroup.FirstOrDefault(a => a.Code.Equals(name, StringComparison.OrdinalIgnoreCase));
                //if (group == null)
                //    return Content(string.Format("Widget Group {0} not found!", name));

                var widgets = db.Widget.Include(a => a.WidgetDetail).Include(w=>w.ArticleType)
                    .Where(a => a.WidgetGroup.Code.Equals(name,StringComparison.OrdinalIgnoreCase))
                    .OrderBy(a => a.WidgetsortOrder).ToList();
                
                PageContext.AddWidgets ( widgets);

                ViewEngineResult result = ViewEngines.Engines.FindView(ControllerContext, "GroupWidget", null);
                if (result.View != null)
                    return PartialView("GroupWidget", widgets);
                else
                    return Content(string.Format("Widget Group {0} not found!", name));

            }
        }
    }
}

VCMS.MVC4.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using VCMS.MVC4.Web.Areas.Admin.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - VCMS Administrator</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/admincss")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <!--[if lt IE 9]>
    @Scripts.Render("~/bundles/Fixie")
         <![endif]-->

</head>
<body class="menu-ontop">
    <header id="header">
        <div id="logo">
            <p class="site-title">@Html.ActionLink("vcms administrator", "Index", "Home")</p>
        </div>
        <div id="login" class="pull-right">
            @Html.Partial("_LoginPartial")
        </div>
    </header>
    <aside id="left-panel">
        @{Html.RenderPartial("_Menu");}
    </aside>
    <div id="main" role="main">
        <div id="ribbon">
            <div id="hide-menu" class="btn-header pull-left hidden-lg hidden-md">
                <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu" class="click-menu"><i class="fa fa-cog"></i></a> </span>
            </div>
            @{Html.RenderPartial("_Breadcrumb");}
        </div>
        <div id="content">
            @RenderBody()
        </div>
    </div>
    <footer>
        @Html.Partial("_Footer")
    </footer>
    <section id="sys-notification" style="display:none;">
        <div class="alert alert-success"><i class="fa fa-exclamation-circle"></i> Post Thành công!.<button type="button" class="close" data-dismiss="alert" aria-label="Close">×</button></div>
    </section>
    <div class="modal fade" id="auopost-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div>
    @Scripts.Render("~/bundles/admin")
    @Scripts.Render("~/bundles/dcaccordion")
    @Scripts.Render("~/bundles/vcms")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/ckeditor/ckeditor.js")
    <script type="text/javascript">
        CKEDITOR_BASEPATH = "@Url.Content("~/Scripts/ckeditor/")";
    </script>

    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $(".click-menu").click(function () {
                $("body").toggleClass("hidden-menu");
            });

        });
        //$(window).load(function () {
        //    var h = $("#left-panel").height() + 250;
        //    if (h > $("#main").height()) {
        //        $("#main").height(h);
        //        $("#left-panel").height($("#main").height());
        //    }
        //});
        //$(window).resize(function () {
        //    $("#main,#left-panel").removeAttr("style");
        //    if ($(window).width() < 767) {
        //        var h = $("#left-panel").height() + 250;
        //        if (h > $("#main").height()) {
        //            $("#main").height(h);
        //            $("#left-panel").height($("#main").height());
        //        }
        //    }
        //    else {
        //        var h = $("#left-panel").height();
        //        if (h < $("#main").height()) {
        //            $("#left-panel").height($("#main").height());
        //        }
        //        else {
        //            $("#main").height(h);
        //        }
        //    }

        //})
        //$('.action a').tooltip()
    </script>
    <!--[if lt IE 9]>
    @Scripts.Render("~/Scripts/Froala/froala_editor_ie8.min.js")
         <![endif]-->
</body>
</html>

VCMS.MVC4.Web/Areas/Admin/Views/Shared/_Breadcrumb.cshtml
@using VCMS.MVC4.Web.Models

@{
    var model = (BreadcrumbModel)ViewBag.Breadcrumb;
    if (model == null)
    {
        model = new BreadcrumbModel();
    }
}

<ul class="breadcrumb @(model.CssClass)">
    @if (model.Items == null || model.Items.Count == 0) // no item, only home text renderred
    {
        <li class="first last"><span>Home</span></li>
    }
    else
    {
        foreach (var item in model.Items)
        {
            if (item.IsLast)
            {
                <li class="last"><span>@item.Text</span></li>
            }
            else
            {
                <li><a href="@item.Url">@item.Text</a></li>
            }
        }
    }
</ul>

VCMS.MVC4.Web/Areas/Admin/Views/Shared/_Footer.cshtml
<style>
    .content-wrapper a {
        color: #fff !important;
    }
    footer .content-wrapper p{
        margin-bottom: 5px;
        font-size: 14px;
    }
    footer .content-wrapper p.link{
        display: inline-block;
        margin-right: 10px;
    }
</style>
<footer>
    <div class="content-wrapper">
        <div class="float-left">
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> 114/40 Tô Ngọc Vân, Phường Thạnh Xuân, Quận 12, TP. Hồ Chí Minh</p>
            <p><i class="fa fa-phone" aria-hidden="true"></i> Tư vấn & hỗ trợ kỹ thuật qua điện thoại:<a href="tel:0913536461">0913536461</a> - <a href="tel:0862576674" style="color: #fff;">0862576674</a> </p>
            <p class="link"><i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:hotro@viennam.com"> hotro@viennam.com</a></p>
            <p class="link"><i class="fa fa-skype" aria-hidden="true"></i> skype: <a href="skype:viennam.contact?chat">viennam.contact</a>​</p>
            <p>&copy; @DateTime.Now.Year - vcms administrator</p>
        </div>
    </div>
</footer>

VCMS.MVC4.Web/Areas/Admin/Views/Shared/_Menu.cshtml
@using VCMS.MVC4.Data
@using VCMS.MVC4.Web
@using System.Data.Entity;
@{
    var db = new DataContext();
    var categorytype = db.CategoryTypes.Include(a => a.CategoryTypeDetail).Where(a => a.NoneType).ToList();
    var articleType = (ViewBag.ArticleType as ArticleType);
}
<nav>
    <ul id="menu-accordion" class="accordion">
        <li>
            <a href="@Url.Action("Index", "Home", new { area="Admin"})">
                <i class="fa fa-home fa-lg fa-fw"></i> @SiteConfig.SiteInfo.WebsiteDetail[SiteConfig.LanguageId].Name
            </a>
        </li>
        @if (Roles.IsUserInRole("Super Administrators"))
        {
            <li>
                <a><i class="fa fa-thumb-tack fa-lg fa-fw"></i> <span class="menu-item-parent">Widget</span></a>
                <ul>
                    <li>@Html.ActionLink("Danh sách", "Index", "Widget")</li>
                    @if (Roles.IsUserInRole("Super Administrators"))
                    {
                        <li>@Html.ActionLink("Danh sách Nhóm", "Group", "Widget")</li>
                    }
                </ul>
            </li>
            Html.RenderAction("Menu", "ArticleType");
            <li>
                <a><i class="fa fa-shopping-cart fa-lg fa-fw"></i> <span class="menu-item-parent">Quản lý giá</span></a>
                <ul>
                    <li>@Html.ActionLink("Quản lý Currency", "CurrencyList", "Price")</li>
                    <li>@Html.ActionLink("Quản lý giảm giá", "Index", "Discount")</li>
                </ul>
            </li>
            if (SiteConfig.CurrentUser.UserName == "admin" || SiteConfig.CurrentUser.UserName == "sa")
            {
                <li>
                    <a><i class="fa fa-table fa-lg fa-fw"></i> <span class="menu-item-parent">Đơn hàng</span></a>
                    <ul>
                        <li>@Html.ActionLink("Danh sách", "Index", "Order")</li>
                        <li>@Html.ActionLink("Cancelled", "Index", "Order", new { status = OrderStatus.CANCELLED }, null)</li>
                    </ul>
                </li>
            }

            if (categorytype.Count > 0)
            {
                <li>
                    <a><i class="fa fa-list-alt"></i> <span class="menu-item-parent">Nhóm riêng</span></a>
                    <ul>
                        @foreach (var item in categorytype)
                        {
                            item.LanguageId = 1;
                            if (!item.Code.Equals("SHIPPINGTIME", StringComparison.Ordinal))
                            {
                                <li><a href="@Url.Action("ListByCateType", "Category", new { id = item.Id })" title="">@item.Name</a></li>
                            }
                            else
                            {
                                <li><a href="@Url.Action("ListByCateType", "Category", new { id = item.Id })" title="">@item.Name</a></li>
                            }
                        }
                    </ul>
                </li>
            }

            <li>
                <a><i class="fa fa-globe fa-lg fa-fw"></i> <span class="menu-item-parent">Quản lý thành viên</span></a>
                <ul>
                    <li><a href="@Url.Action("Index", "User", new { role = "Administrators" })" title="">Quản trị chung</a></li>
                    <li><a href="@Url.Action("Index", "User", new { role = "Moderators" })" title="">Quyền đăng bài</a></li>
                    <li><a href="@Url.Action("Index", "User", new { role = "Users" })" title="">Người dùng</a></li>
                </ul>
            </li>
            <li>
                <a><i class="fa fa-globe fa-lg fa-fw"></i> <span class="menu-item-parent">Thông tin website</span></a>
                <ul>
                    <li>@Html.ActionLink("Loại bài viết", "Index", "ArticleType")</li>
                    <li>@Html.ActionLink("Quản lý menu", "Index", "Menu")</li>
                    <li>@Html.ActionLink("Quản lý nhóm riêng", "ListCateType", "Category")</li>
                    <li>@Html.ActionLink("Quản lý thuộc tính", "Index", "Property")</li>
                    <li>@Html.ActionLink("Quản lý ngôn ngữ", "Index", "Language")</li>
                    <li>@Html.ActionLink("Quản lý Locales", "Index", "Locale")</li>
                    <li>@Html.ActionLink("Update Database", "UpdateDatabase", "Website")</li>
                    <li>@Html.ActionLink("Cấu hình", "Index", "Website")</li>
                    @*<li>@Html.ActionLink("Thống kê", "Online", "Website")</li>*@
                </ul>
            </li>
        }
        else if (Roles.IsUserInRole("Administrators"))
        {
            <li>
                <a><i class="fa fa-thumb-tack fa-lg fa-fw"></i> <span class="menu-item-parent">Widget</span></a>
                <ul>
                    <li>@Html.ActionLink("Danh sách", "Index", "Widget")</li>
                    @if (Roles.IsUserInRole("Super Administrators"))
                    {
                        <li>@Html.ActionLink("Danh sách Nhóm", "Group", "Widget")</li>
                    }
                </ul>
            </li>
            Html.RenderAction("Menu", "ArticleType");
            @*if (SiteConfig.SiteInfo.HasShoppingCart)
            {
                <li>
                    <a><i class="fa fa-shopping-cart fa-lg fa-fw"></i> <span class="menu-item-parent">Quản lý giá</span></a>
                    <ul>
                        <li>@Html.ActionLink("Quản lý Currency", "CurrencyList", "Price")</li>
                        @if (SiteConfig.SiteInfo.HasDiscount)
                        {
                            <li>@Html.ActionLink("Quản lý giảm giá", "Index", "Discount")</li>
                        }
                    </ul>
                </li>
            }*@
            if (SiteConfig.SiteInfo.HasOrder)
            {
                <li>
                    <a><i class="fa fa-table fa-lg fa-fw"></i> <span class="menu-item-parent">Đơn hàng</span></a>
                    <ul>
                        <li>@Html.ActionLink("Danh sách", "Index", "Order")</li>
                        @*<li>@Html.ActionLink("Cancelled", "Index", "Order", new { status = OrderStatus.CANCELLED }, null)</li>*@
                    </ul>
                </li>
            }
            if (categorytype.Count > 0)
            {
                <li>
                    <a><i class="fa fa-list-alt"></i> <span class="menu-item-parent">Nhóm riêng</span></a>
                    <ul>
                        @foreach (var item in categorytype)
                        {
                            item.LanguageId = 1;
                            if (!item.Code.Equals("SHIPPINGTIME", StringComparison.Ordinal))
                            {
                                <li><a href="@Url.Action("ListByCateType", "Category", new { id = item.Id })" title="">@item.Name</a></li>
                            }
                        }
                    </ul>
                </li>
            }
            if (SiteConfig.SiteInfo.HasUser)
            {
                <li>
                    <a><i class="fa fa-user fa-lg fa-fw"></i> <span class="menu-item-parent">Quản lý thành viên</span></a>
                    <ul>
                        @*<li><a href="@Url.Action("Index", "User", new { role = "Administrators" })" title="">Quản trị chung</a></li>*@
                        <li><a href="@Url.Action("Index", "User", new { role = "Moderators" })" title="">Quyền đăng bài</a></li>
                        @*<li><a href="@Url.Action("Index", "User", new { role = "Users" })" title="">Người dùng</a></li>*@
                    </ul>
                </li>
            }
            <li>
                <a><i class="fa fa-globe fa-lg fa-fw"></i> <span class="menu-item-parent">Thông tin website</span></a>
                <ul>
                    <li>@Html.ActionLink("Cấu hình", "Index", "Website")</li>
                    <li>@Html.ActionLink("Thống kê", "Online", "Website")</li>
                </ul>
            </li>
        }
        else if (Roles.IsUserInRole("Moderators"))
        {
            Html.RenderAction("Menu", "ArticleType");
        }
    </ul>
</nav>
<span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>
<script type="text/javascript">
    $(function () {
        $("#menu-accordion").dcAccordion({
            eventType: 'click',
            autoClose: true,
            saveState: true,
            disableLink: true,
            showCount: false,
            speed: 'fast',
            skin: 'demo'
        });
        $("#menu-accordion a[href*='@Request.Path']").addClass('selected');
    })
</script>

VCMS.MVC4.Web/Areas/Admin/Views/Shared/_Menu1.cshtml
@using VCMS.MVC4.Data
@using VCMS.MVC4.Web
@using System.Data.Entity;
@{
    var db = new DataContext();
    var categorytype = db.CategoryTypes.Include(a => a.CategoryTypeDetail).Where(a => a.NoneType).ToList();
}
<nav>
    <ul id="menu-accordion" class="accordion">
        <li>
            <a href="@Url.Action("Index", "Home", new { area="Admin"})">
                <i class="fa fa-home fa-lg fa-fw"></i> @SiteConfig.SiteInfo.WebsiteDetail[SiteConfig.LanguageId].Name
            </a>
        </li>
        @if (Roles.IsUserInRole("Super Administrators") || Roles.IsUserInRole("Administrators"))
        {
            <li>
                <a><i class="fa fa-thumb-tack fa-lg fa-fw"></i> <span class="menu-item-parent">Widget</span></a>
                <ul>
                    <li>@Html.ActionLink("Danh sách", "Index", "Widget")</li>
                    @if (Roles.IsUserInRole("Super Administrators"))
                    {
                        <li>@Html.ActionLink("Danh sách Nhóm", "Group", "Widget")</li>
                    }
                </ul>
            </li>
        }

        @{
            Html.RenderAction("Menu", "ArticleType");
        }
        @if (SiteConfig.SiteInfo.HasShoppingCart)
        {
            if (Roles.IsUserInRole("Super Administrators") || Roles.IsUserInRole("Administrators"))
            {
                <li>
                    @if (Roles.IsUserInRole("Super Administrators")|| SiteConfig.SiteInfo.HasDiscount)
                    {
                         <a><i class="fa fa-shopping-cart fa-lg fa-fw"></i> <span class="menu-item-parent">Quản lý giá</span></a>
                    }
                    <ul>
                        @if (Roles.IsUserInRole("Super Administrators"))
                        {
                            <li>@Html.ActionLink("Quản lý Currency", "CurrencyList", "Price")</li>
                        }
                        @if(SiteConfig.SiteInfo.HasDiscount)
                        {
                             <li>@Html.ActionLink("Quản lý giảm giá", "Index", "Discount")</li>
                        }
                    </ul>
                </li>
            }
            if (SiteConfig.SiteInfo.HasOrder)
            {
                if (!Roles.IsUserInRole("Moderators"))
                {
                    <li>
                        <a><i class="fa fa-table fa-lg fa-fw"></i> <span class="menu-item-parent">Đơn hàng</span></a>
                        <ul>
                            <li>@Html.ActionLink("Danh sách", "Index", "Order")</li>
                            @*<li>@Html.ActionLink("Cancelled", "Index", "Order", new { status = OrderStatus.CANCELLED }, null)</li>*@
                        </ul>
                    </li>
                }
            }


        }
        @if (categorytype.Count > 0)
        {
            <li>
                <a><i class="fa fa-list-alt"></i> <span class="menu-item-parent">Nhóm riêng</span></a>
                <ul>
                    @foreach (var item in categorytype)
                    {
                        item.LanguageId = 1;
                        if (!item.Code.Equals("SHIPPINGTIME", StringComparison.Ordinal))
                        {
                            <li><a href="@Url.Action("ListByCateType", "Category", new { id = item.Id })" title="">@item.Name</a></li>
                        }
                        else
                        {
                            if (Roles.IsUserInRole("Super Administrators"))
                            {
                                <li><a href="@Url.Action("ListByCateType", "Category", new { id = item.Id })" title="">@item.Name</a></li>
                            }
                        }
                    }
                </ul>
            </li>
        }
        @if (!Roles.IsUserInRole("Moderators") && (SiteConfig.SiteInfo.HasUser || SiteConfig.SiteInfo.HasNewsletter))
        {
            <li>
                <a>
                    <i class="fa fa-users fa-lg fa-fw"></i> <span class="menu-item-parent">
                        @(SiteConfig.SiteInfo.HasNewsletter && !SiteConfig.SiteInfo.HasUser && !Roles.IsUserInRole("Super Administrators") ? "Email Khuyến mãi" : "Quản lý người dùng")
                    </span>
                </a>
                <ul>

                    @if (Roles.IsUserInRole("Super Administrators") || SiteConfig.CurrentUser.UserName == "admindocsach")
                    {
                        <li><a href="@Url.Action("Index", "User", new { role = "Administrators" })" title="">Quản trị</a></li>
                        <li><a href="@Url.Action("Index", "User", new { role = "Moderators" })" title="">Nhân viên</a></li>
                        <li><a href="@Url.Action("Index", "User", new { role = "Users" })" title="">Người dùng</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Index", "User", new { role = "Moderators" })" title="">Nhân viên</a></li>
                        @*<li><a href="@Url.Action("Index", "User", new { role = "Users" })" title="">Người dùng</a></li>*@
                    }
                    @*@if (SiteConfig.SiteInfo.HasNewsletter)
                        {
                            <li><a href="@Url.Action("Index", "User", new { role = "Guests" })" title="">Email nhận tin khuyến mãi</a></li>
                        }*@
                </ul>
            </li>
        }
        @if (Roles.IsUserInRole("Super Administrators") || Roles.IsUserInRole("Administrators"))
        {
            <li>
                <a><i class="fa fa-globe fa-lg fa-fw"></i> <span class="menu-item-parent">Thông tin website</span></a>
                <ul>
                    @if (Roles.IsUserInRole("Super Administrators"))
                    {
                        <li>@Html.ActionLink("Loại bài viết", "Index", "ArticleType")</li>
                        <li>@Html.ActionLink("Quản lý menu", "Index", "Menu")</li>
                        <li>@Html.ActionLink("Quản lý nhóm riêng", "ListCateType", "Category")</li>
                        <li>@Html.ActionLink("Quản lý thuộc tính", "Index", "Property")</li>
                        <li>@Html.ActionLink("Quản lý ngôn ngữ", "Index", "Language")</li>
                        <li>@Html.ActionLink("Quản lý Locales", "Index", "Locale")</li>
                        <li>@Html.ActionLink("Update Database", "UpdateDatabase", "Website")</li>
                    }


                    <li>@Html.ActionLink("Cấu hình", "Index", "Website")</li>
                    @if (Roles.IsUserInRole("Super Administrators"))
                    {
                        <li>@Html.ActionLink("Thống kê", "Online", "Website")</li>
                    }



                </ul>
            </li>
        }

    </ul>
</nav>
<span class="minifyme" data-action="minifyMenu"> <i class="fa fa-arrow-circle-left hit"></i> </span>
<script type="text/javascript">
    $(function () {
        $("#menu-accordion").dcAccordion({
            eventType: 'click',
            autoClose: true,
            saveState: true,
            disableLink: true,
            showCount: false,
            speed: 'fast',
            skin: 'demo'
        });
        $("#menu-accordion a[href*='@Request.Path']").addClass('selected');
    })
</script>