VCMS.MVC4.Web/Areas/Admin/Controllers/LocaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VCMS.MVC4.Data;
using System.Data.Entity;
using VCMS.MVC4.Web;
using EntityFramework.Extensions;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.IO;
using Newtonsoft.Json.Linq;
using System.Drawing;
namespace VCMS.MVC4.Web.Areas.Admin.Controllers
{
    public class LocaleController : VCMSAdminController
    {
        //
        // GET: /Admin/Locale/
        public ActionResult Index()
        {
            using (DataContext db = new DataContext())
            {
                return View(db.Locales.Include(l => l.LocaleDetail).OrderBy(l => l.LocaleKey).ToList());
            }
        }
        public ActionResult Create()
        {
            Locale l = new Locale() { LocaleDetail = VList<LocaleDetail>.Create(SiteConfig.Languages) };
            return View(l);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection form)
        {
            using (DataContext db = new DataContext())
            {
                var text = form["LocaleKey"];
                if (string.IsNullOrWhiteSpace(text))
                {
                    return Json(new { Status = 0, Message = "Không để trống Từ khóa." });
                }
                var query = db.Locales.FirstOrDefault(a => a.LocaleKey == text);
                if (query != null)
                {
                    return Json(new { Status = 0, Message = "Từ khóa đã tồn tại." });
                }
                Locale local = new Locale() { LocaleKey = form["LocaleKey"], DefaultValue = form["DefaultValue"], LocaleDetail = VList<LocaleDetail>.Create(SiteConfig.Languages) };
                foreach (var l in SiteConfig.Languages)
                {
                    local.LocaleDetail[l.Id].Value = form["LocaleDetail[" + l.Id + "].Value"];
                }
                db.Locales.Add(local);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            using (DataContext db = new DataContext())
            {
                var model = db.Locales.Include(l => l.LocaleDetail).Where(p => p.Id == id).FirstOrDefault();
                var missing = SiteConfig.Languages.Where(l => !model.LocaleDetail.Any(cd => cd.LanguageId == l.Id)).Select(l => l.Id).ToList();
                missing.ForEach(m => { model.LocaleDetail.Add(new LocaleDetail { LanguageId = m }); });
                return View(model);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection form)
        {
            using (DataContext db = new DataContext())
            {
                var loc = db.Locales.Include(l => l.LocaleDetail).FirstOrDefault(l => l.Id == id);
                TryUpdateModel(loc);
                var details = from d in SiteConfig.Languages
                              select new LocaleDetail()
                              {
                                  LanguageId = d.Id,
                                  Value = form["LocaleDetail[" + d.Id + "].Value"]
                              };
                loc.LocaleDetail = new VList<LocaleDetail>();
                loc.LocaleDetail.AddRange(details);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            using (DataContext db = new DataContext())
            {
                int[] ids = id.Split(new char[] { ',' }).Select(s => int.Parse(s)).ToArray();
                db.Locales.Delete(l => ids.Contains((int)l.Id));

                db.SaveChanges();
                return Json(new { Status = 0, Message = "OK" });
            }
        }
        public ActionResult Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Import(FormCollection form)
        {
            using (DataContext db = new DataContext())
            {
                List<Locale> LocaleList = new List<Locale>();
                var html = new HtmlHelper(new ViewContext(ControllerContext, new WebFormView(ControllerContext, "empty"), new ViewDataDictionary(), new TempDataDictionary(), new System.IO.StringWriter()), new ViewPage());

                if (Request.Files["Import"] != null)
                {
                    #region Upload File
                    string[] allowdFile = { ".xls", ".xlsx", ".xml" };
                    string ext = Path.GetExtension(Request.Files["Import"].FileName);
                    string filename = Request.Files["Import"].FileName;

                    bool isValidFile = allowdFile.Contains(ext);
                    if (!isValidFile)
                        return Json(new { error = html.Locale("locale_error_import_file").ToHtmlString() });

                    var filePath = Path.Combine(SiteConfig.UploadFolder, "Data");
                    var physicalPath = System.Web.HttpContext.Current.Server.MapPath(filePath);

                    if (!Directory.Exists(physicalPath))
                        Directory.CreateDirectory(physicalPath);

                    FileInfo newFile = new FileInfo(Path.Combine(physicalPath, filename));
                    if (newFile.Exists)
                    {
                        newFile.Delete();
                        newFile = new FileInfo(Path.Combine(physicalPath, filename));
                    }

                    Request.Files["Import"].SaveAs(Path.Combine(physicalPath, filename));
                    #endregion
                    if (ext == ".xls" || ext == ".xlsx")
                    {
                        using (ExcelPackage xlPackage = new ExcelPackage(newFile))
                        {
                            ExcelWorkbook wkb = xlPackage.Workbook;
                            if (wkb != null)
                            {
                                for (int i = 1; i < wkb.Worksheets.Count + 1; i++)
                                {
                                    int startRow = 2;
                                    ExcelWorksheet currentworksheet = wkb.Worksheets[i];
                                    if (!currentworksheet.Cells["A1"].Value.Equals("ID") ||
                                        !currentworksheet.Cells["B1"].Value.Equals("Mã") ||
                                        !currentworksheet.Cells["C1"].Value.Equals("Giá trị mặc định"))
                                        continue;
                                    for (int rowNumber = startRow; rowNumber <= currentworksheet.Dimension.End.Row; rowNumber++)
                                    {
                                        int col = 1;
                                        int id = 0;
                                        if (!string.IsNullOrWhiteSpace(currentworksheet.Cells[rowNumber, col].Text))
                                            id = int.Parse(currentworksheet.Cells[rowNumber, col++].Text.Split('.').FirstOrDefault());
                                        else col += 1;
                                        var locale = db.Locales.Include(a => a.LocaleDetail).Where(a => a.Id == id).FirstOrDefault();

                                        string lkey = currentworksheet.Cells[rowNumber, col].Text;
                                        if (string.IsNullOrWhiteSpace(lkey))
                                            continue;

                                        if (locale != null)
                                        {
                                            #region Update Locale
                                            locale.LocaleKey = currentworksheet.Cells[rowNumber, col++].Text;
                                            locale.DefaultValue = currentworksheet.Cells[rowNumber, col++].Text;
                                            foreach (var lg in SiteConfig.Languages)
                                            {
                                                locale.LocaleDetail[lg.Id].LanguageId = lg.Id;
                                                locale.LocaleDetail[lg.Id].Value = currentworksheet.Cells[rowNumber, col++].Text;
                                            }
                                            db.SaveChanges();
                                            #endregion
                                        }
                                        else
                                        {
                                            col = 2;
                                            #region Insert Locale
                                            var localekey = db.Locales.Where(a => a.LocaleKey == lkey).FirstOrDefault();
                                            if (localekey != null)
                                                continue;
                                            var model = new Locale()
                                            {
                                                LocaleDetail = VList<LocaleDetail>.Create(SiteConfig.Languages)
                                            };

                                            model.LocaleKey = currentworksheet.Cells[rowNumber, col++].Text;
                                            model.DefaultValue = currentworksheet.Cells[rowNumber, col++].Text;
                                            foreach (var lg in SiteConfig.Languages)
                                            {
                                                model.LocaleDetail[lg.Id].LanguageId = lg.Id;
                                                model.LocaleDetail[lg.Id].Value = currentworksheet.Cells[rowNumber, col++].Text;
                                            }
                                            db.Locales.Add(model);

VCMS.MVC4.Web/Areas/Admin/Views/Locale/Create.cshtml
@using VCMS.MVC4.Web
@using VCMS.MVC4.Data
@model VCMS.MVC4.Data.Locale

@{
    ViewBag.Title = "Thêm Mới";
}
@section styles{
    @Styles.Render("~/Content/themes/base/css")
}

<div class="form">

    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Locale</legend>
            <div class="editor-label">
                @Html.LabelFor(model => model.LocaleKey)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.LocaleKey)
                @Html.ValidationMessageFor(model => model.LocaleKey)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.DefaultValue)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.DefaultValue)
                @Html.ValidationMessageFor(model => model.DefaultValue)
            </div>
            @foreach (var l in SiteConfig.Languages)
            {
                <div class="editor-label">
                    @Html.Label("Value - " + l.DisplayName)
                </div>
                <div id="tabs-@l.Id">
                    @Html.TextAreaFor(model => model.LocaleDetail[l.Id].Value, new { cols = "20" })
                </div>
            }
            <div class="toolbar">
                <span class="button">
                    <button type="submit" class="btn save"><i class="fa fa-save"></i> Lưu</button>
                </span>
                <span class="btn back">
                    <a href="@Url.Action("Index",null,null)">
                        <i class="fa fa-mail-reply"></i> <span>Trở về</span>
                    </a>
                </span>
            </div>
        </fieldset>
    }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/editor")
        <script>
            $(".form form").submit(function (event) {
                event.preventDefault();
                var obj = $(this);
                $.ajax({
                    url: "@Url.Action("Create")",
                    type: "post",
                    data: obj.serialize(),
                    success: function (data) {
                        if (data.Status == 0) {
                            alert(data.Message);
                        }
                        else {
                            window.location.href = '@Url.Action("Index")';
                        }
                    }
                });
            });
        </script>
    }
</div>

VCMS.MVC4.Web/Areas/Admin/Views/Locale/Edit.cshtml
@using VCMS.MVC4.Web
@model VCMS.MVC4.Data.Locale
@{
    ViewBag.Title = "Edit";
}
<div class="form">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Locale</legend>
            @Html.HiddenFor(model => model.Id)
            <div class="editor-label">
                @Html.LabelFor(model => model.LocaleKey)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.LocaleKey)
                @Html.ValidationMessageFor(model => model.LocaleKey)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.DefaultValue)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.DefaultValue)
                @Html.ValidationMessageFor(model => model.DefaultValue)
            </div>
            @foreach (var l in SiteConfig.Languages)
            {
                <div class="editor-label">
                    @Html.Label("Value - " + l.DisplayName)
                </div>
                <div id="tabs-@l.Id">
                    @Html.TextAreaFor(model => model.LocaleDetail[l.Id].Value)
                </div>
            }
            <div class="toolbar">
                <span class="button">
                    <button type="submit" class="btn save"><i class="fa fa-save"></i> Save</button>
                </span>
                <span class="btn back">
                    <a href="@Url.Action("Index",null,null)">
                        <i class="fa fa-mail-reply"></i> <span>Trở về</span>
                    </a>
                </span>
            </div>
        </fieldset>
    }
</div>

VCMS.MVC4.Web/Areas/Admin/Views/Locale/Import.cshtml
@using VCMS.MVC4.Extensions
@{
    Layout = null;
    ViewBag.Title = "Import Locale";
    ViewBag.Breadcrumb = new BreadcrumbModel()
    {
        Items = new List<BreadcrumbItem>()
        {
            new BreadcrumbItem(){Url = Url.Action("Index","Home"), Text="Trang chủ", IsFirst=true},
            new BreadcrumbItem(){Url = Url.Action("Index","Locale"), Text="Danh sách chuỗi", IsLast = true},
        }
    };
}
<div class="modal-dialog">
    <div class="form no-boder-radius import">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Đóng</span></button>
            <h4 class="modal-title" id="myModalLabel">Import Locale</h4>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm(null, null, null, FormMethod.Post, new { id = "locale-form", enctype = "multipart/form-data" }))
            {
                <div class="editor-label">
                    @Html.Label("Chọn file Import")
                </div>
                <div class="editor-field file article">
                    @Html.TextBox("Import", null, new { type = "file", data_val = "true" })<i data-label="Chọn file"></i>
                    @Html.ValidationMessage("Import")
                </div>
                <div id=""></div>
                <div class="toolbar">
                    <span class="button">
                        <button id="button-locale-import" type="submit" class="btn save"><i class="fa fa-save"></i> Upload</button>
                    </span>
                </div>
            }
        </div>
    </div>
</div>

<script>
    $("#button-locale-import").on("click", function () {
        var _this = $(this);
        var data = new FormData();
        var files = $("#Import").get(0).files;

        if (files.length > 0) {
            data.append("Import", files[0]);
        }

        $.ajax({
            url: '@Url.Action("Import","Locale")',
            data: data,
            type: "post",
            //dataType: "json",
            contentType: false,
            processData: false,
            success: function (json) {
                $('.alert, .text-danger').remove();
                if (json['redirect'])
                    location = json['redirect'];
                else if (json['error']) {
                    
                    $('.modal-body').prepend('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error'] + '<button type="button" class="close" data-dismiss="alert">&times;</button></div>');
                }
                return false;
            }, error: function (xhr, ajaxOptions, thrownError) {
                alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
            }
        });
        return false;
    });
</script>

VCMS.MVC4.Web/Areas/Admin/Views/Locale/Index.cshtml
@model ICollection<Locale>
@{

    ViewBag.Title = "Danh sách chuỗi";
    ViewBag.Breadcrumb = new BreadcrumbModel()
    {
        Items = new List<BreadcrumbItem>()
        {
            new BreadcrumbItem(){Url = Url.Action("Index","Home"), Text="Home", IsFirst=true},
            new BreadcrumbItem(){Url = Url.Action("Index","Locale"), Text="Danh sách chuỗi", IsLast = true},
        }
    };
    var db = new DataContext();
}
<div class="btn-group">
    <span class="btn create">
        <a href="@Url.Action("Create",null,null)"><i class="fa fa-plus"></i> <span class="hidden-xs">Thêm mới</span></a>
    </span>
    <span class="btn delete">
        <a href="@Url.Action("Delete", null, null)" id="delete"><i class="fa fa-trash-o"></i> <span class="hidden-xs">Xóa</span></a>
    </span>
    <span class="btn import">
        <a href="@Url.Action("Import", "Locale")" data-toggle="modal" data-target="#locale-form">
            <i class="fa fa-plus"></i> <span>Import from Excel</span>
        </a>
    </span>
    <div class="btn-group btn type">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" id="button-action">
            <i class="fa fa-table"></i>
            Export to Excel
        </a>
        <ul class="dropdown-menu fa-ul">
            <li>
                <a href="@Url.Action("Export", "Locale")">
                    <i class="fa fa-align-justify fs15"></i> <span>Tất cả</span>
                </a>
            </li>
            <li>
                <a href="#" id="export-select">
                    <i class="fa fa-magic fs15"></i> <span>Tùy chọn</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<table class="table table-hover">
    <thead class="header">
        <tr>
            <th class="check">
                <label class="checkbox single noborder">
                    <input type="checkbox" id="check-all" /><i></i>
                </label>
            </th>
            <th class="hidden-xs code language">
                @Html.Label("Mã")
            </th>
            <th class="titles">
                @Html.Label("Giá trị mặc định")
            </th>
            @foreach (var l in SiteConfig.Languages)
            {
            <th class="titles">@l.DisplayName</th>
            }
            <th class="action">
                @Html.Label("Thao tác")
            </th>
        </tr>
    </thead>
    <tbody class="items">
        @foreach (var item in Model)
        {
            <tr class="item">
                <td class="check">
                    <label class="checkbox fix"><input type="checkbox" value="@item.Id" class="check-export" /><i></i></label>
                </td>
                <td class="code language">@item.LocaleKey</td>
                <td class="titles">@Html.Raw(item.DefaultValue)</td>
                @foreach (var l in SiteConfig.Languages)
                {
                    if (item.LocaleDetail.FirstOrDefault(a => a.LocaleId == item.Id && a.LanguageId == l.Id) != null)
                    {
                        <td class="titles">
                            @Html.Raw(item.LocaleDetail.FirstOrDefault(a => a.LocaleId == item.Id && a.LanguageId == l.Id).Value)
                        </td>
                    }
                    else
                    {
                        <td class="titles" title=""></td>
                    }
                }
                <td class="action">
                    <a href="@Url.Action("Edit", null, new {id=item.Id })"><i class="fa fa-edit"></i> <span class="hidden-xs">Edit</span></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="locale-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @{Html.RenderAction("Import", "Locale");}
</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("#check-all").checkAll(".item .check input[type='checkbox']");
        });
        $(".check-export").change(function () {
            $(this).parentsUntil(".items").find(".check input[type='checkbox']").addClass("changed");
        });
        $("#export-select").on("click", function () {
            $('a#button-action').trigger('click');
            var json = [];
            $(".item .check input[type='checkbox'].changed").each(function () {
                json.push({ "id": $(this).val() });
            });
            if (json.length > 0) {
                $.ajax({
                    url: '@Url.Action("ExportSelect")',
                    type: 'POST',
                    success: function (json) {
                        if (json['error'])
                            alert(json['error']['warning']);
                        else if (json['redirect'])
                            location = json['redirect'];
                    },
                    data: "json=" + JSON.stringify(json)
                });
            }
            else
                alert('Lựa chọn chuỗi từ khóa cần Export.');
            return false;
        });
        $("#delete").sdelete({
            url: '@Url.Action("Delete")',
            selector: ".item .check input[type='checkbox']",
        });
    </script>
}